export const DATE
export const COMPANY_PAN
export const EMPLOYEE_ID
export const DATE_OF_JOINING
export const HAS_SEPERATED
export const DATE_OF_SEPERATION
export const BANK_NAME
export const BANK_ACCOUNT_NO
export const MONTHLY_GROSS
export const MONTHLY_BASIC
export const DAYS_MONTH
export const DAYS_PAYABLE
export const PAN
export const OPENING
export const EARNED
export const AVAILED
export const CLOSING
export const BASIC
export const CONVEYANCE_ALLOWANCE
export const INCENTIVE
export const INCOME_TAX
export const ARREARS